- id: lavender
  name: lavender
  description: "Lavender: The slightly more compromising Python code formatter"
  entry: lavender
  language: python
  language_version: python3
  require_serial: true
  types: [python]
